# NumPy: Array Object Exercises

In [1]:
import numpy as np

**2.1.Write a NumPy program to print the NumPy version in your system.**

In [2]:
# solution for exercise 2.1.
np.__version__

'1.19.2'

**2.2.Write a NumPy program to convert a list of numeric value into a one-dimensional NumPy array.**

In [4]:
# solution for exercise 2.2.
a = {1, 2, 3, 4}


**2.3.Write a NumPy program to create a 3x3 matrix with values ranging from 2 to 10.**

In [5]:
# solution for exercise 2.3.
np.arange(2, 11).reshape(3, 3)

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

**2.4.Write a NumPy program to create a null vector of size 10 and update sixth value to 11.**

In [8]:
# solution exercise 2.4.
a = np.zeros(10)
a[7] = 11
print(a)

[ 0.  0.  0.  0.  0.  0.  0. 11.  0.  0.]


**2.5.Write a NumPy program to create an array with values ranging from 12 to 38.**

In [10]:
# soultion for exercise 2.5.
np.arange(12, 38)

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28,
       29, 30, 31, 32, 33, 34, 35, 36, 37])

**2.6.Write a NumPy program to reverse an array (first element becomes last).**

In [14]:
# solution for exercise 2.6.
a = np.arange(1, 10)

print('original array:', a, '\n', 'reversed:', a[::-1])

original array: [1 2 3 4 5 6 7 8 9] 
 reversed: [9 8 7 6 5 4 3 2 1]


**2.7.Write a NumPy program to convert an array to a float type.**

In [15]:
# solution for exercise 2.8.
np.arange(1, 10, dtype = 'float32')

array([1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=float32)

**2.8.Write a NumPy program to create a 2d array with 1 on the border and 0 inside.**

In [30]:
# soultion for exercise 2.8.
a = np.ones(45).reshape(9, 5)

a[1: -1, 1: -1] = 0

print(a)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


**2.9.Write a NumPy program to add a border (filled with 0's) around an existing array.**

In [50]:
# solution for exercise 2.9.
a = np.ones(45).reshape(9, 5)

np.pad(a, pad_width = 1, mode = 'constant', constant_values = 0)

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])