# Numpy

Fast and versatile, the NumPy vectorization, indexing, and broadcasting concepts are the de-facto standards of array computing today.

NumPy offers comprehensive mathematical functions, random number generators, linear algebra routines, Fourier transforms, and more.

NumPy supports a wide range of hardware and computing platforms, and plays well with distributed, GPU, and sparse array libraries.

The core of NumPy is well-optimized C code. Enjoy the flexibility of Python with the speed of compiled code.

NumPy’s high level syntax makes it accessible and productive for programmers from any background or experience level.

### 1. NumPy Basic: Exercises, Practice, Solution

**1.1.Write a NumPy program to get the numpy version and show numpy build configuration.**

In [1]:
# package
import numpy as np

# solution for exercise 1.1.
print(np.__version__)
print(np.show_config())

1.19.2
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/ProgramData/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/ProgramData/Anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/ProgramData/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/ProgramData/Anaconda3\\Library\\include']
lapack_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/ProgramData/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/ProgramData/Anaconda3\\Library\\include']
lapack_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/ProgramData/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/ProgramData/Anaconda3\\Library\\include']
None


**1.2. Write a NumPy program to  get help on the add function.**

In [2]:
# solution exercise 1.2.
print(np.info(np.add))

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

**1.3. Write a NumPy program to test whether none of the elements of a given array is zero.**

In [3]:
# solution exercise 1.3.

# function
def any_zero_(x):
    '''This program test if have wheter none of the elements given in x is zero.
    any_zero_(x) x should be a number or group of numbers'''
    return np.all(x)

# 2 data elements
a = [4, 6, 2, 10]
b = [1, 0, 4, 2]

# run program
print(any_zero_(a)) # expectec False
print('\n') # spaces between answers
print(any_zero_(b)) # expectet True

True


False


**1.4. Write a NumPy program to test whether any of the elements of a given array is non-zero.**

In [4]:
# solution exercise 1.4

# function A
def noany_zero_(x):
    '''This program test if have wheter any of the elements given in x is zero.
    any_zero_(x) x should be a number or group of numbers'''
    return (~(np.all(x)))

# funtion B
def noany_zero_2(x):
    '''This program test if have wheter any of the elements given in x is zero.
    any_zero_(x) x should be a number or group of numbers'''
    return np.any(x)

# run program
 
%timeit noany_zero_(a) # expectec True


# %timeit noany_zero_2(b) # expectec False

5.96 µs ± 283 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [5]:
# it's faster function 2 (expected)
%timeit noany_zero_2(b) # expectec False

4.96 µs ± 140 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


**1.5. Write a NumPy program to test a given array element-wise for finiteness (not infinity or not a Number).**

In [6]:
# solution exercise 1.5.

# function 
def is_finite(x):
    '''Function for determinates if one number X is finite
    is_finite(x)'''
    return np.isfinite(x)

# data 
a = 1000

# run function
is_finite(a)

True

**1.6.Write a NumPy program to test element-wise for positive or negative infinity.**

In [7]:
# soultion for exercise 1.6

# data 
a = np.random.normal(10, 20, 10)
a[4] = np.inf

# run numpy command
np.isinf(a)

array([False, False, False, False,  True, False, False, False, False,
       False])

**1.7.Write a NumPy program to test element-wise for NaN of a given array.**

In [8]:
# solution for exercise 1.7.
a = np.random.normal(10, 20, 100)
a[::3] = np.nan

# run numpy command
np.isnan(a[::2])

array([ True, False, False,  True, False, False,  True, False, False,
        True, False, False,  True, False, False,  True, False, False,
        True, False, False,  True, False, False,  True, False, False,
        True, False, False,  True, False, False,  True, False, False,
        True, False, False,  True, False, False,  True, False, False,
        True, False, False,  True, False])

**1.8.Write a NumPy program to test element-wise for complex number, real number of a given array. Also test whether a given number is a scalar type or not.**

In [9]:
# solution exercise 1.8.
a = 3
print('Is complex:', np.iscomplex(a), '\n', 'Is real:', 
      np.isreal(a), '\n', 'Is scalar:', np.isscalar(a))

Is complex: False 
 Is real: True 
 Is scalar: True


**1.9.Write a NumPy program to test whether two arrays are element-wise equal within a tolerance.**

In [10]:
a = 1.99999999999999999999999999999999999999
b = 1 + .999999999999999999999999999999999999

# solution exercise 9
np.allclose(a, b)

True

**1.10.Write a NumPy program to create an element-wise comparison (greater, greater_equal, less and less_equal) of two given arrays.**

In [11]:
# create matrix
a = np.arange(25).reshape(5, 5)
b = np.random.normal(12, 5, 25).reshape(5, 5)

print(a, '\n', b)

# compare
print('\n', 'B values greater than A:', '\n', np.greater(a, b))
print('\n', 'B values greater-equal than A:', '\n', np.greater_equal(a, b))
print('\n', 'B values less-equal than A:', '\n', np.less_equal(a, b))
print('\n', 'B values less than A:', '\n', np.less(a, b))

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]] 
 [[ 7.35715686 12.39032349 14.08637762 15.48334643 16.15680175]
 [ 5.4644975   9.32192887  5.50400188 14.96867496 14.65129032]
 [18.25305332  8.54629543 12.70236166 12.3576958  19.4243617 ]
 [14.42101142 18.50444975 -0.46228998  8.54603427  8.35043291]
 [ 9.08616513  7.80092201 14.09844105  4.52777627 12.82500482]]

 B values greater than A: 
 [[False False False False False]
 [False False  True False False]
 [False  True False  True False]
 [ True False  True  True  True]
 [ True  True  True  True  True]]

 B values greater-equal than A: 
 [[False False False False False]
 [False False  True False False]
 [False  True False  True False]
 [ True False  True  True  True]
 [ True  True  True  True  True]]

 B values less-equal than A: 
 [[ True  True  True  True  True]
 [ True  True False  True  True]
 [ True False  True False  True]
 [False  True False False False]
 [False False False False False

In [12]:
# note the diference of time in running
%timeit np.greater(a, b)
%timeit a > b

1.64 µs ± 25.1 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)
1.67 µs ± 126 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


**1.11.Write a NumPy program to create an element-wise comparison (equal, equal within a tolerance) of two given arrays.**

In [21]:
# solution for exercise 1.11
# data
a = np.random.normal(5, .1, 50).reshape(10, 5)
b = np.random.normal(5, .1, 50).reshape(10, 5)
c = np.arange(25).reshape(5, 5)
d = c.copy()

# equal
print('All equal exactly:', np.equal(c, d[::-1]))

# equal with tolerante
print('\n', 'All equal:', np.allclose(a, b))
print('\n', 'All equal:', np.allclose(c, d[::-1]))

All equal exactly: [[False False False False False]
 [False False False False False]
 [ True  True  True  True  True]
 [False False False False False]
 [False False False False False]]

 All equal: False

 All equal: False


**1.12.Write a NumPy program to create an array with the values 1, 7, 13, 105 and determine the size of the memory occupied by the array.**

In [29]:
# solution for exercise 1.12
# create a array with number 1, 7, 13, 105
a = np.array([1, 7, 13, 105])

# memory loc
print(a, '\n', a.size * a.itemsize, ' bytes')

[  1   7  13 105] 
 16  bytes


**1.13.Write a NumPy program to create an array of 10 zeros,10 ones, 10 fives.**

In [33]:
# solution for exercise 1.13.
print(np.zeros(10))
print('\n')
print(np.ones(10))
print('\n')
print(np.ones(10) * 5)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


**1.14.Write a NumPy program to create an array of the integers from 30 to70.**

In [35]:
# solution for exercise 1.14.
print(np.arange(30, 71))

[30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70]


**1.15.Write a NumPy program to create an array of all the even integers from 30 to 70.**

In [43]:
# solution for exercise 1.15.
print(np.arange(30, 71, 2))

[30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68 70]


**1.16.Write a NumPy program to create a 3x3 identity matrix.**

In [44]:
# soultion for exercise 1.16.
# identity matrix
np.eye(3, 3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

**1.17.Write a NumPy program to generate a random number between 0 and 1.**

In [57]:
# solution for exercise 1.17.
np.random.rand(1)

array([0.99617169])