# NumPy: Array Object Exercises

In [2]:
import numpy as np

**2.1.Write a NumPy program to print the NumPy version in your system.**

In [2]:
# solution for exercise 2.1.
np.__version__

'1.19.2'

**2.2.Write a NumPy program to convert a list of numeric value into a one-dimensional NumPy array.**

In [4]:
# solution for exercise 2.2.
a = {1, 2, 3, 4}


**2.3.Write a NumPy program to create a 3x3 matrix with values ranging from 2 to 10.**

In [5]:
# solution for exercise 2.3.
np.arange(2, 11).reshape(3, 3)

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

**2.4.Write a NumPy program to create a null vector of size 10 and update sixth value to 11.**

In [8]:
# solution exercise 2.4.
a = np.zeros(10)
a[7] = 11
print(a)

[ 0.  0.  0.  0.  0.  0.  0. 11.  0.  0.]


**2.5.Write a NumPy program to create an array with values ranging from 12 to 38.**

In [10]:
# soultion for exercise 2.5.
np.arange(12, 38)

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28,
       29, 30, 31, 32, 33, 34, 35, 36, 37])

**2.6.Write a NumPy program to reverse an array (first element becomes last).**

In [14]:
# solution for exercise 2.6.
a = np.arange(1, 10)

print('original array:', a, '\n', 'reversed:', a[::-1])

original array: [1 2 3 4 5 6 7 8 9] 
 reversed: [9 8 7 6 5 4 3 2 1]


**2.7.Write a NumPy program to convert an array to a float type.**

In [15]:
# solution for exercise 2.8.
np.arange(1, 10, dtype = 'float32')

array([1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=float32)

**2.8.Write a NumPy program to create a 2d array with 1 on the border and 0 inside.**

In [30]:
# soultion for exercise 2.8.
a = np.ones(45).reshape(9, 5)

a[1: -1, 1: -1] = 0

print(a)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


**2.9.Write a NumPy program to add a border (filled with 0's) around an existing array.**

In [50]:
# solution for exercise 2.9.
a = np.ones(45).reshape(9, 5)

np.pad(a, pad_width = 1, mode = 'constant', constant_values = 0)

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

**2.10.Write a NumPy program to create a 8x8 matrix and fill it with a checkerboard pattern.**

In [62]:
# solution for exercise 2.10.
a = np.zeros(64).reshape(8, 8)
a[::2, 1::2] = 1
a[1::2, ::2] = 1

print(a)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


**2.11.Write a NumPy program to convert a list and tuple into arrays.**

In [7]:
# solution for exercise 2.11.
a = [1, 6, 3]
b = [[7, 7], [9, 9]]

aa = np.asarray(a)
bb = np.asarray(b)

print(a, '\n', b)

[1, 6, 3] 
 [[7, 7], [9, 9]]


**2.12.Write a NumPy program to append values to the end of an array.**

In [10]:
# solution for exercise 2.12.
a = np.array([1, 6, 3])
np.append(a, [7, 3, 5])

array([1, 6, 3, 7, 3, 5])

**2.13.Write a NumPy program to create an empty and a full array.**

In [17]:
# solution for exercise 2.13.
a = np.empty((5, 5))
b = np.full((6, 6), 5)

print(a, '\n', b)

[[6.23042070e-307 3.56043053e-307 1.60219306e-306 7.56571288e-307
  1.89146896e-307]
 [1.37961302e-306 1.05699242e-307 8.01097889e-307 1.78020169e-306
  7.56601165e-307]
 [1.02359984e-306 1.42417221e-306 1.42419530e-306 1.37962456e-306
  1.11260959e-306]
 [1.78021527e-306 1.69119330e-306 2.22523140e-306 1.78018811e-306
  1.69120552e-306]
 [1.29062025e-306 1.37961709e-306 2.22522596e-306 2.22522596e-306
  2.22809558e-312]] 
 [[5 5 5 5 5 5]
 [5 5 5 5 5 5]
 [5 5 5 5 5 5]
 [5 5 5 5 5 5]
 [5 5 5 5 5 5]
 [5 5 5 5 5 5]]


**2.14.Write a NumPy program to convert the values of Centigrade degrees into Fahrenheit degrees. Centigrade values are stored into a NumPy array.**

In [19]:
# solution exercise 2.14.
c = np.asarray([4, 26, 33, 18])

print((c *  (9 / 5)) + 32)

[39.2 78.8 91.4 64.4]


**2.15.Write a NumPy program to find the real and imaginary parts of an array of complex numbers.**

In [24]:
# solution for exercise 2.15.
a = np.asarray([1 +3j, 4 + 3j], dtype = 'complex')

print('part real:', np.real(a), 'part imaginary:', np.imag(a))

part real: [1. 4.] part imaginary: [3. 3.]


**2.16.Write a NumPy program to find the number of elements of an array, length of one array element in bytes and total bytes consumed by the elements.**

In [5]:
# solution for exercise 2.16.
a = np.random.normal(10, 3, 50). reshape(10, 5)

s = a.size
i = a.itemsize
b = a.nbytes

print('size: {} \nitem size: {} \nbytes size: {}'.format(s, i, b))

size: 50 
item size: 8 
bytes size: 400


**2.17.Write a NumPy program to test whether each element of a 1-D array is also present in a second array.**

In [14]:
# solution for exercise 2.17.
a = np.arange(15)
b = np.arange(15)[::-1]
c = np.arange(10, 25)

print(np.in1d(a, b))
print(np.in1d(a, c))

[ True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True]
[False False False False False False False False False False  True  True
  True  True  True]


**2.18.Write a NumPy program to find common values between two arrays.**

In [16]:
# solution for exercise 2.18.
a = np.arange(5, 15)
b = np.arange(2, 9)

print(np.intersect1d(a, b))

[5 6 7 8]
