# Numpy

Fast and versatile, the NumPy vectorization, indexing, and broadcasting concepts are the de-facto standards of array computing today.

NumPy offers comprehensive mathematical functions, random number generators, linear algebra routines, Fourier transforms, and more.

NumPy supports a wide range of hardware and computing platforms, and plays well with distributed, GPU, and sparse array libraries.

The core of NumPy is well-optimized C code. Enjoy the flexibility of Python with the speed of compiled code.

NumPy’s high level syntax makes it accessible and productive for programmers from any background or experience level.

### 1. NumPy Basic: Exercises, Practice, Solution

**1.1.Write a NumPy program to get the numpy version and show numpy build configuration.**

In [1]:
# package
import numpy as np

# solution for exercise 1.1.
print(np.__version__)
print(np.show_config())

1.19.2
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/ProgramData/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/ProgramData/Anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/ProgramData/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/ProgramData/Anaconda3\\Library\\include']
lapack_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/ProgramData/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/ProgramData/Anaconda3\\Library\\include']
lapack_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/ProgramData/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/ProgramData/Anaconda3\\Library\\include']
None


**1.2. Write a NumPy program to  get help on the add function.**

In [2]:
# solution exercise 1.2.
print(np.info(np.add))

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

**1.3. Write a NumPy program to test whether none of the elements of a given array is zero.**

In [3]:
# solution exercise 1.3.

# function
def any_zero_(x):
    '''This program test if have wheter none of the elements given in x is zero.
    any_zero_(x) x should be a number or group of numbers'''
    return np.all(x)

# 2 data elements
a = [4, 6, 2, 10]
b = [1, 0, 4, 2]

# run program
print(any_zero_(a)) # expectec False
print('\n') # spaces between answers
print(any_zero_(b)) # expectet True

True


False


**1.4. Write a NumPy program to test whether any of the elements of a given array is non-zero.**

In [4]:
# solution exercise 1.4

# function A
def noany_zero_(x):
    '''This program test if have wheter any of the elements given in x is zero.
    any_zero_(x) x should be a number or group of numbers'''
    return (~(np.all(x)))

# funtion B
def noany_zero_2(x):
    '''This program test if have wheter any of the elements given in x is zero.
    any_zero_(x) x should be a number or group of numbers'''
    return np.any(x)

# run program
 
%timeit noany_zero_(a) # expectec True


# %timeit noany_zero_2(b) # expectec False

6.92 µs ± 560 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [5]:
# it's faster function 2 (expected)
%timeit noany_zero_2(b) # expectec False

6.2 µs ± 353 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


**1.5. Write a NumPy program to test a given array element-wise for finiteness (not infinity or not a Number).**

In [6]:
# solution exercise 1.5.

# function 
def is_finite(x):
    '''Function for determinates if one number X is finite
    is_finite(x)'''
    return np.isfinite(x)

# data 
a = 1000

# run function
is_finite(a)

True

**1.6.Write a NumPy program to test element-wise for positive or negative infinity.**

In [7]:
# soultion for exercise 1.6

# data 
a = np.random.normal(10, 20, 10)
a[4] = np.inf

# run numpy command
np.isinf(a)

array([False, False, False, False,  True, False, False, False, False,
       False])

**1.7.Write a NumPy program to test element-wise for NaN of a given array.**

In [8]:
# solution for exercise 1.7.
a = np.random.normal(10, 20, 100)
a[::3] = np.nan

# run numpy command
np.isnan(a[::2])

array([ True, False, False,  True, False, False,  True, False, False,
        True, False, False,  True, False, False,  True, False, False,
        True, False, False,  True, False, False,  True, False, False,
        True, False, False,  True, False, False,  True, False, False,
        True, False, False,  True, False, False,  True, False, False,
        True, False, False,  True, False])

**1.8.Write a NumPy program to test element-wise for complex number, real number of a given array. Also test whether a given number is a scalar type or not.**

In [14]:
# solution exercise 1.8.
a = 3
print('Is complex:', np.iscomplex(a), '\n', 'Is real:', 
      np.isreal(a), '\n', 'Is scalar:', np.isscalar(a))

Is complex: False 
 Is real: True 
 Is scalar: True


**1.9.Write a NumPy program to test whether two arrays are element-wise equal within a tolerance.**

In [15]:
a = 1.99999999999999999999999999999999999999
b = 1 + .999999999999999999999999999999999999

# solution exercise 9
np.allclose(a, b)

True

**1.10.Write a NumPy program to create an element-wise comparison (greater, greater_equal, less and less_equal) of two given arrays.**

In [35]:
# create matrix
a = np.arange(25).reshape(5, 5)
b = np.random.normal(12, 5, 25).reshape(5, 5)

print(a, '\n', b)

# compare
print('\n', 'B values greater than A:', '\n', np.greater(a, b))
print('\n', 'B values greater-equal than A:', '\n', np.greater_equal(a, b))
print('\n', 'B values less-equal than A:', '\n', np.less_equal(a, b))
print('\n', 'B values less than A:', '\n', np.less(a, b))

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]] 
 [[10.58438573  8.51418054  4.35296931 10.78509369 12.29677337]
 [ 7.82603291 18.14158183  8.28764169 17.72640396 10.2851471 ]
 [ 4.11188281 24.19263238 11.60125853 11.48136487  7.07384672]
 [15.79790019 15.09136738 19.21571569 -0.31974365  6.27486673]
 [ 7.16844847  3.37485322  8.67382243  9.74992535 11.19622683]]

 B values greater than A: 
 [[False False False False False]
 [False False False False False]
 [ True False  True  True  True]
 [False  True False  True  True]
 [ True  True  True  True  True]]

 B values greater-equal than A: 
 [[False False False False False]
 [False False False False False]
 [ True False  True  True  True]
 [False  True False  True  True]
 [ True  True  True  True  True]]

 B values less-equal than A: 
 [[ True  True  True  True  True]
 [ True  True  True  True  True]
 [False  True False False False]
 [ True False  True False False]
 [False False False False False

In [46]:
# note the diference of time in running
%timeit np.greater(a, b)
%timeit a > b

1.24 µs ± 20.4 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)
1.18 µs ± 20.3 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)
