# Numpy

Fast and versatile, the NumPy vectorization, indexing, and broadcasting concepts are the de-facto standards of array computing today.

NumPy offers comprehensive mathematical functions, random number generators, linear algebra routines, Fourier transforms, and more.

NumPy supports a wide range of hardware and computing platforms, and plays well with distributed, GPU, and sparse array libraries.

The core of NumPy is well-optimized C code. Enjoy the flexibility of Python with the speed of compiled code.

NumPy’s high level syntax makes it accessible and productive for programmers from any background or experience level.

### 1. NumPy Basic: Exercises, Practice, Solution

**1.1.Write a NumPy program to get the numpy version and show numpy build configuration.**

In [1]:
# package
import numpy as np

# solution for exercise 1.1.
print(np.__version__)
print(np.show_config())

1.19.2
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/ProgramData/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/ProgramData/Anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/ProgramData/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/ProgramData/Anaconda3\\Library\\include']
lapack_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/ProgramData/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/ProgramData/Anaconda3\\Library\\include']
lapack_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/ProgramData/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/ProgramData/Anaconda3\\Library\\include']
None


**1.2. Write a NumPy program to  get help on the add function.**

In [2]:
# solution exercise 1.2.
print(np.info(np.add))

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

**1.3. Write a NumPy program to test whether none of the elements of a given array is zero.**

In [3]:
# solution exercise 1.3.

# function
def any_zero_(x):
    '''This program test if have wheter none of the elements given in x is zero.
    any_zero_(x) x should be a number or group of numbers'''
    return np.all(x)

# 2 data elements
a = [4, 6, 2, 10]
b = [1, 0, 4, 2]

# run program
print(any_zero_(a)) # expectec False
print('\n') # spaces between answers
print(any_zero_(b)) # expectet True

True


False


**1.4. Write a NumPy program to test whether any of the elements of a given array is non-zero.**

In [4]:
# solution exercise 1.4

# function A
def noany_zero_(x):
    '''This program test if have wheter any of the elements given in x is zero.
    any_zero_(x) x should be a number or group of numbers'''
    return (~(np.all(x)))

# funtion B
def noany_zero_2(x):
    '''This program test if have wheter any of the elements given in x is zero.
    any_zero_(x) x should be a number or group of numbers'''
    return np.any(x)

# run program
 
%timeit noany_zero_(a) # expectec True


# %timeit noany_zero_2(b) # expectec False

6.08 µs ± 398 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [5]:
# it's faster function 2 (expected)
%timeit noany_zero_2(b) # expectec False

4.93 µs ± 184 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


**1.5. Write a NumPy program to test a given array element-wise for finiteness (not infinity or not a Number).**

In [6]:
# solution exercise 1.5.

# function 
def is_finite(x):
    '''Function for determinates if one number X is finite
    is_finite(x)'''
    return np.isfinite(x)

# data 
a = 1000

# run function
is_finite(a)

True

**1.6.Write a NumPy program to test element-wise for positive or negative infinity.**

In [7]:
# soultion for exercise 1.6

# data 
a = np.random.normal(10, 20, 10)
a[4] = np.inf

# run numpy command
np.isinf(a)

array([False, False, False, False,  True, False, False, False, False,
       False])

**1.7.Write a NumPy program to test element-wise for NaN of a given array.**

In [8]:
# solution for exercise 1.7.
a = np.random.normal(10, 20, 100)
a[::3] = np.nan

# run numpy command
np.isnan(a[::2])

array([ True, False, False,  True, False, False,  True, False, False,
        True, False, False,  True, False, False,  True, False, False,
        True, False, False,  True, False, False,  True, False, False,
        True, False, False,  True, False, False,  True, False, False,
        True, False, False,  True, False, False,  True, False, False,
        True, False, False,  True, False])

**1.8.Write a NumPy program to test element-wise for complex number, real number of a given array. Also test whether a given number is a scalar type or not.**

In [9]:
# solution exercise 1.8.
a = 3
print('Is complex:', np.iscomplex(a), '\n', 'Is real:', 
      np.isreal(a), '\n', 'Is scalar:', np.isscalar(a))

Is complex: False 
 Is real: True 
 Is scalar: True


**1.9.Write a NumPy program to test whether two arrays are element-wise equal within a tolerance.**

In [10]:
a = 1.99999999999999999999999999999999999999
b = 1 + .999999999999999999999999999999999999

# solution exercise 9
np.allclose(a, b)

True

**1.10.Write a NumPy program to create an element-wise comparison (greater, greater_equal, less and less_equal) of two given arrays.**

In [11]:
# create matrix
a = np.arange(25).reshape(5, 5)
b = np.random.normal(12, 5, 25).reshape(5, 5)

print(a, '\n', b)

# compare
print('\n', 'B values greater than A:', '\n', np.greater(a, b))
print('\n', 'B values greater-equal than A:', '\n', np.greater_equal(a, b))
print('\n', 'B values less-equal than A:', '\n', np.less_equal(a, b))
print('\n', 'B values less than A:', '\n', np.less(a, b))

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]] 
 [[10.10960591  4.91989177  8.51917789 10.9150191  13.83326753]
 [10.47118081  8.34300313  9.75690949 14.07697209  6.88093594]
 [18.550012    9.97634369 19.65514347 17.10506659 -1.88200566]
 [12.4095231   4.22170805  8.01671572 14.29123017 13.82840746]
 [11.7053393  15.35085236  9.56177497 15.04585562 12.72183235]]

 B values greater than A: 
 [[False False False False False]
 [False False False False  True]
 [False  True False False  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]]

 B values greater-equal than A: 
 [[False False False False False]
 [False False False False  True]
 [False  True False False  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]]

 B values less-equal than A: 
 [[ True  True  True  True  True]
 [ True  True  True  True False]
 [ True False  True  True False]
 [False False False False False]
 [False False False False False

In [12]:
# note the diference of time in running
%timeit np.greater(a, b)
%timeit a > b

1.11 µs ± 39.3 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)
1.09 µs ± 12.2 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


**1.11.Write a NumPy program to create an element-wise comparison (equal, equal within a tolerance) of two given arrays.**

In [13]:
# solution for exercise 1.11
# data
a = np.random.normal(5, .1, 50).reshape(10, 5)
b = np.random.normal(5, .1, 50).reshape(10, 5)
c = np.arange(25).reshape(5, 5)
d = c.copy()

# equal
print('All equal exactly:', np.equal(c, d[::-1]))

# equal with tolerante
print('\n', 'All equal:', np.allclose(a, b))
print('\n', 'All equal:', np.allclose(c, d[::-1]))

All equal exactly: [[False False False False False]
 [False False False False False]
 [ True  True  True  True  True]
 [False False False False False]
 [False False False False False]]

 All equal: False

 All equal: False


**1.12.Write a NumPy program to create an array with the values 1, 7, 13, 105 and determine the size of the memory occupied by the array.**

In [14]:
# solution for exercise 1.12
# create a array with number 1, 7, 13, 105
a = np.array([1, 7, 13, 105])

# memory loc
print(a, '\n', a.size * a.itemsize, ' bytes')

[  1   7  13 105] 
 16  bytes


**1.13.Write a NumPy program to create an array of 10 zeros,10 ones, 10 fives.**

In [15]:
# solution for exercise 1.13.
print(np.zeros(10))
print('\n')
print(np.ones(10))
print('\n')
print(np.ones(10) * 5)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


**1.14.Write a NumPy program to create an array of the integers from 30 to70.**

In [16]:
# solution for exercise 1.14.
print(np.arange(30, 71))

[30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70]


**1.15.Write a NumPy program to create an array of all the even integers from 30 to 70.**

In [17]:
# solution for exercise 1.15.
print(np.arange(30, 71, 2))

[30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68 70]


**1.16.Write a NumPy program to create a 3x3 identity matrix.**

In [18]:
# soultion for exercise 1.16.
# identity matrix
np.eye(3, 3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

**1.17.Write a NumPy program to generate a random number between 0 and 1.**

In [19]:
# solution for exercise 1.17.
np.random.rand(1)

array([0.92637184])

**1.18.Write a NumPy program to generate an array of 15 random numbers from a standard normal distribution.**

In [20]:
# soultion for exercise 1.18.
np.random.normal(0, 1, 15).reshape(3, 5)

array([[ 0.00708907, -0.4723369 , -1.38977114, -0.3835426 , -1.37420684],
       [ 0.31474311, -0.84561494, -0.65928771, -0.26634947, -0.91772935],
       [-0.29653332,  0.93291028,  0.38065662, -0.42811235,  0.85959501]])

**1.19.Write a NumPy program to create a vector with values ranging from 15 to 55 and print all values except the first and last.**

In [21]:
# solution for exercise 1.19.
np.arange(15, 55)[1: -1]

array([16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32,
       33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49,
       50, 51, 52, 53])

**1.20.Write a NumPy program to create a 3X4 array using and iterate over it.**

In [22]:
# soultion for exercise 1.20.
np.arange(0, 12).reshape(3, 4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

**1.21.Write a NumPy program to create a vector of length 10 with values evenly distributed between 5 and 50.**

In [23]:
# solution for exercise 1.21.
np.arange(5, 50, 2)

array([ 5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35, 37,
       39, 41, 43, 45, 47, 49])

**1.22.Write a NumPy program to create a vector with values from 0 to 20 and change the sign of the numbers in the range from 9 to 15.**

In [33]:
# solution for exercise 1.22.
a = np.arange(0, 20)
a[(a > 9) & (a < 15)] = a[(a > 9) & (a < 15)] * -1

print(a)

[  0   1   2   3   4   5   6   7   8   9 -10 -11 -12 -13 -14  15  16  17
  18  19]


**1.23.Write a NumPy program to create a vector of length 5 filled with arbitrary integers from 0 to 10.**

In [34]:
# solution for exercise 1.23.
np.random.randint(0, 10, 5)

array([2, 2, 0, 7, 7])

**1.24.Write a NumPy program to multiply the values of two given vectors.**

In [36]:
# solucion exercise 1.24.
a = np.random.randint(1, 25, 10)
b = np.random.randint(1, 25, 10)

# product
np.multiply(a, b)

array([230, 176, 399, 162, 414,  91, 273,  64, 154, 210])

**1.25.Write a NumPy program to create a 3x4 matrix filled with values from 10 to 21.**

In [38]:
# soultion for exercise 1.25.
np.arange(10, 22).reshape(3, 4)

array([[10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21]])

**1.26.Write a NumPy program to find the number of rows and columns of a given matrix.**

In [44]:
# solution for exercise 1.26.
# matrix
a = np.zeros(25).reshape(5, 5)
a.shape

(5, 5)

**1.27.Write a NumPy program to create a 3x3 identity matrix, i.e. diagonal elements are 1, the rest are 0.**

In [45]:
# solution for exercise 1.27.
np.eye(3, 3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

**1.28.Write a NumPy program to create a 10x10 matrix, in which the elements on the borders will be equal to 1, and inside 0.**

In [52]:
# solution for exercise 1.28.
a = np.ones(100).reshape(10, 10)
a[1:9, 1:9] -= 1
a

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

**1.29.Write a NumPy program to create a 5x5 zero matrix with elements on the main diagonal equal to 1, 2, 3, 4, 5.**

In [60]:
# solution for exercise 1.29.
np.diag(range(1, 6))

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

**1.30.Write a NumPy program to create a 4x4 matrix in which 0 and 1 are staggered, with zeros on the main diagonal.**

In [126]:
# soultion for exercise 1.30.
x = np.zeros((4, 4))
x[::2, 1::2] = 1
x[1::2, ::2] = 1

print(x)

[[0. 1. 0. 1.]
 [1. 0. 1. 0.]
 [0. 1. 0. 1.]
 [1. 0. 1. 0.]]


**1.31.Write a NumPy program to create a 3x3x3 array filled with arbitrary values.**

In [127]:
# soultion for exercise 1.31.
np.random.randint(1, 99, 27).reshape(3, 3, 3)

array([[[75, 54, 72],
        [78, 47, 25],
        [40, 98, 95]],

       [[49, 57, 17],
        [62, 64, 43],
        [70, 60, 90]],

       [[97,  9, 28],
        [24, 61, 71],
        [46, 65,  2]]])

**1.32.Write a NumPy program to compute sum of all elements, sum of each column and sum of each row of a given array.**

In [132]:
# soultion for exercise 1.33.
# data 
a = np.random.randint(1, 25, 25).reshape(5, 5)
print('row sum:', a.sum(axis = 0), '\n', 'column sum:', a.sum(axis = 1))

row sum: [66 83 64 78 50] 
 column sum: [88 38 60 70 85]


**1.33.Write a NumPy program to compute the inner product of two given vectors.**

In [133]:
# solution for exercise 1.33.
a = np.random.randint(1, 5, 25)
b = np.random.randint(1, 5, 25)

a.dot(b)

156

**1.34.Write a NumPy program to add a vector to each row of a given matrix.**

In [150]:
# solution for exercise 1.34.
# matrix
a = np.random.randint(1, 100, 50).reshape(5, 10)
# vector
b = np.random.randint(1, 100, 10)

# sum each row
a + b 

array([[180, 160, 148,  85, 114, 190,  96, 145, 190,  85],
       [175, 178, 168,  92, 120, 193,  54, 134,  94,  76],
       [133, 102,  98, 149, 166, 135,  81, 106, 158, 141],
       [173, 193, 181,  82, 117, 188,  57,  98, 180, 139],
       [186, 136, 120, 136, 169, 175,  33, 133, 149, 110]])

**1.35.Write a NumPy program to save a given array to a binary file.**

In [170]:
# solution for exercise 1.35.
a = np.random.randint(1, 6, 10)
print(a, '\n', ['{0:08b}'.format(i) for i in a])

[2 1 5 3 5 5 1 5 1 4] 
 ['00000010', '00000001', '00000101', '00000011', '00000101', '00000101', '00000001', '00000101', '00000001', '00000100']
